# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca8c124ffa7f282ff42fc10ccad26e3b575fe8c5a2f85a3ae0927a2ef61d652a2c5c04df395fcf14fdb1c490772203ce3c3e222bfb5c001ebe4d82502044c28c

test:
  secret_key_base: 3e449e17efaa71cb86c08a3961bdcba6a8d3d114930890aeb90d26ba1039cecb8e4432b6cd24ac4f93317d41f5414272f9c5ab232e210b45f22e8439f366be30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
